/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnternehmenRouteImport } from './routes/unternehmen'
import { Route as ReferenzenRouteImport } from './routes/referenzen'
import { Route as PrivatpersonenRouteImport } from './routes/privatpersonen'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AvgsCoachingRouteImport } from './routes/avgs-coaching'
import { Route as R16kCoachingRouteImport } from './routes/16k-coaching'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachesSlugRouteImport } from './routes/coaches.$slug'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const UnternehmenRoute = UnternehmenRouteImport.update({
  id: '/unternehmen',
  path: '/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRoute = ReferenzenRouteImport.update({
  id: '/referenzen',
  path: '/referenzen',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatpersonenRoute = PrivatpersonenRouteImport.update({
  id: '/privatpersonen',
  path: '/privatpersonen',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AvgsCoachingRoute = AvgsCoachingRouteImport.update({
  id: '/avgs-coaching',
  path: '/avgs-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const R16kCoachingRoute = R16kCoachingRouteImport.update({
  id: '/16k-coaching',
  path: '/16k-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesSlugRoute = CoachesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoachesRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/16k-coaching': typeof R16kCoachingRoute
  '/avgs-coaching': typeof AvgsCoachingRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/privatpersonen': typeof PrivatpersonenRoute
  '/referenzen': typeof ReferenzenRoute
  '/unternehmen': typeof UnternehmenRoute
  '/coaches/$slug': typeof CoachesSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/16k-coaching': typeof R16kCoachingRoute
  '/avgs-coaching': typeof AvgsCoachingRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/privatpersonen': typeof PrivatpersonenRoute
  '/referenzen': typeof ReferenzenRoute
  '/unternehmen': typeof UnternehmenRoute
  '/coaches/$slug': typeof CoachesSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/16k-coaching': typeof R16kCoachingRoute
  '/avgs-coaching': typeof AvgsCoachingRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/privatpersonen': typeof PrivatpersonenRoute
  '/referenzen': typeof ReferenzenRoute
  '/unternehmen': typeof UnternehmenRoute
  '/coaches/$slug': typeof CoachesSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/16k-coaching'
    | '/avgs-coaching'
    | '/coaches'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/privatpersonen'
    | '/referenzen'
    | '/unternehmen'
    | '/coaches/$slug'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/16k-coaching'
    | '/avgs-coaching'
    | '/coaches'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/privatpersonen'
    | '/referenzen'
    | '/unternehmen'
    | '/coaches/$slug'
    | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/16k-coaching'
    | '/avgs-coaching'
    | '/coaches'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/privatpersonen'
    | '/referenzen'
    | '/unternehmen'
    | '/coaches/$slug'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R16kCoachingRoute: typeof R16kCoachingRoute
  AvgsCoachingRoute: typeof AvgsCoachingRoute
  CoachesRoute: typeof CoachesRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  PrivatpersonenRoute: typeof PrivatpersonenRoute
  ReferenzenRoute: typeof ReferenzenRoute
  UnternehmenRoute: typeof UnternehmenRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unternehmen': {
      id: '/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof UnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen': {
      id: '/referenzen'
      path: '/referenzen'
      fullPath: '/referenzen'
      preLoaderRoute: typeof ReferenzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatpersonen': {
      id: '/privatpersonen'
      path: '/privatpersonen'
      fullPath: '/privatpersonen'
      preLoaderRoute: typeof PrivatpersonenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avgs-coaching': {
      id: '/avgs-coaching'
      path: '/avgs-coaching'
      fullPath: '/avgs-coaching'
      preLoaderRoute: typeof AvgsCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/16k-coaching': {
      id: '/16k-coaching'
      path: '/16k-coaching'
      fullPath: '/16k-coaching'
      preLoaderRoute: typeof R16kCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/$slug': {
      id: '/coaches/$slug'
      path: '/$slug'
      fullPath: '/coaches/$slug'
      preLoaderRoute: typeof CoachesSlugRouteImport
      parentRoute: typeof CoachesRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoachesRouteChildren {
  CoachesSlugRoute: typeof CoachesSlugRoute
}

const CoachesRouteChildren: CoachesRouteChildren = {
  CoachesSlugRoute: CoachesSlugRoute,
}

const CoachesRouteWithChildren =
  CoachesRoute._addFileChildren(CoachesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R16kCoachingRoute: R16kCoachingRoute,
  AvgsCoachingRoute: AvgsCoachingRoute,
  CoachesRoute: CoachesRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  PrivatpersonenRoute: PrivatpersonenRoute,
  ReferenzenRoute: ReferenzenRoute,
  UnternehmenRoute: UnternehmenRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
